### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by coderrahul** [vimeo/iris#114]
Below mentioned icons are needed in IRIS

1. ![Screenshot 2022-04-27 at 3 56 59 PM](https://user-images.githubusercontent.com/80899540/165499681-b9cd7f44-a4b2-4e0f-922f-d897b78adce8.png) Mobile.svg
2. ![Screenshot 2022-04-27 at 3 57 06 PM](https://user-images.githubusercontent.com/80899540/165499901-d3f4ad23-1f67-4596-9c33-158c460d7f2a.png) Desktop.svg
3. ![Screenshot 2022-04-27 at 3 58 20 PM](https://user-images.githubusercontent.com/80899540/165499928-28aa4ced-00c8-4f71-bfac-0f4e22e97428.png) Attendee.svg
4. ![Screenshot 2022-04-27 at 4 00 23 PM](https://user-images.githubusercontent.com/80899540/165499969-22bc6e5e-3288-44bb-92e0-9bf8ea76ac5d.png) TextAlignLeft
5. ![Screenshot 2022-04-27 at 4 01 09 PM](https://user-images.githubusercontent.com/80899540/165500005-a85f8796-80f5-4882-8219-1a92dad69574.png) TextAlignCenter
6. ![Screenshot 2022-04-27 at 4 00 30 PM](https://user-images.githubusercontent.com/80899540/165500037-e7a115f2-29e2-45ea-8a3a-79f9439cf87d.png) TextAlignRight
7. ![Screenshot 2022-04-27 at 4 00 37 PM](https://user-images.githubusercontent.com/80899540/165500155-6a7d7b86-6f93-4e19-a8d4-8dd4be0fc600.png) NumberedList

cc: @seanmcintyre

**Comment by seanmcintyre** [comment]
Hello. This is not the appropriate channel to request new icons be added to Iris. Please ask your designer to bring them to the next Design Systems Review meeting.
