### ISSUE TITLE
[BUG]: PopOver does not dismiss on list item clicks

### ISSUE THREAD

**Issue by praneetloke** [vimeo/iris#173]
### Description

I have a popover similar to what you see in the [story](https://vimeo.github.io/iris/sb/main/?path=/docs/components-popover--controls) for that component. The problem is that the menu does not disappear when I click a menu item in the list (also demonstrated in the aforementioned story.) I tried to use the `active` prop to control its open state but that leads to problems since I am trying to use the component in a parent component which itself is a list of cards. This is especially problematic for my use case because I am trying to show a modal when an item in the menu is clicked which leaves the popover component open and it overlays above the Modal. I realize I could adjust the z-index for the popover but I would not like to. Instead, if there was a prop that I could pass to the component to tell it to hide the popover when a child component is clicked, especially a typical case for popovers used to display menus, that would be great!

As an aside, when using the `active` prop the component ignores "outside clicks" which means I needed to pass a `ref` to the component, as well as use your `useOutsideClick` hook to wire things up myself. Not a huge deal but it would be nice if the component didn't ignore outside clicks when `active` is used. I could use `onClose` to sync the external state when that happens.

### Steps to Reproduce

Here's a sample demonstrating the problem with showing a modal while the popover is still open.

```tsx
import { useState } from "react";
import { Button, Modal, PopOver, Pop } from "@vimeo/iris/components";

export function Test() {
  const [showModal, setShowModal] = useState(false);
  return (
    <>
      <PopOver
        content={
          <Pop.List>
            <Pop.Item onClick={() => setShowModal(true)}>Item 1</Pop.Item>
          </Pop.List>
        }
      >
        <Button>Open popover</Button>
      </PopOver>
      <Modal
        active={showModal}
        content={<div>modal content!</div>} onClose={() => setShowModal(false)}
        size="sm"
      />
    </>
  );
}
```

### Version

0.128.0

### What browsers are you seeing the problem on?

Firefox

**Comment by praneetloke** [comment]
Ping. Anyone?

**Comment by tylerthegrove** [comment]
Hey @praneetloke .

We looked into this and will be adding a prop to dismiss the menu on click.

We will also explore calling the onClose prop even when you are controlling the active state of the PopOver. That seems like the correct way for the component to work.

**Comment by praneetloke** [comment]
Awesome, thank you!

**Comment by juliewongbandue** [comment]
Hey @praneetloke! Thanks for bringing this up. You should actually be able to control the `active` prop with an `onClick` on the list item. It's also encouraged that you use the [Modal.minors](https://github.com/vimeo/iris/blob/main/src/components/Modal/Modal.minors.tsx) to compose your modal content. I put together an example here in this [draft pr](https://github.com/vimeo/iris/blob/173-bug-popover/src/components/PopOver/PopOver.story.tsx#L72-L140).

See the deployed story [here](https://github.com/vimeo/iris/pull/190).

Is this the interaction you were looking for?

**Comment by praneetloke** [comment]
@juliewongbandue thank you for adding the example. I took a look. The suggested approach unfortunately would not work when there are multiple PopOver's on a page as part of some parent list component, say, for example, if you had a list of card components each composed of a PopOver component where one of the PopOver menu item should open a Modal.

**Comment by juliewongbandue** [comment]
Hmm, I'm afraid I don't understand what what you mean-- could you recreate this example in a story?

**Comment by praneetloke** [comment]
@juliewongbandue if you have more than one instance of the `Test` component from the issue description it should demonstrate what I am trying to describe. For example,

```tsx
export function List() {
  return (
    <Test />
    <Test />
    <Test />
  );
}
```

**Comment by juliewongbandue** [comment]
Hey @praneetloke ! No worries! So to dismiss the outside click we actually have a `useOutsideClick` hook available that I've included in my example: https://github.com/vimeo/iris/blob/173-bug-popover/src/components/PopOver/PopOver.story.tsx#L106-L108

**Comment by praneetloke** [comment]
@juliewongbandue thank you for that. That seems to work for me. I noticed that the `ref` object wasn't passed to the PopOver component. Is that not strictly necessary? This is what I did:

```tsx
export function MyComp() {
  const ref = useRef(null);
  useOutsideClick(ref, () => {
    // Do something...
  });

  return <PopOver forwardRef={ref} ...><Button icon={<DotsMenu />} /></PopOver>
}
```

**Comment by juliewongbandue** [comment]
Hey @praneetloke, no problem. It is necessary, the `useOutsideClick` hook needs the ref of the component that you want to click outside of: https://github.com/vimeo/iris/blob/main/src/utils/hooks/useOutsideClick.ts

**Comment by praneetloke** [comment]
@juliewongbandue sounds good. Thank you for your help with this!
