### ISSUE TITLE
[BUG]: `useLayoutEffect` warnings in next.js build

### ISSUE THREAD

**Issue by heylookltsme** [vimeo/iris#47]
### Description

We're seeing warnings in our NextJS build: 
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client.
```

### Steps to Reproduce

Run vimeo's NextJS and request a page that uses the minimal footer. 

### Version

0.108.0

**Comment by seanmcintyre** [comment]
If anyone is interested in taking this on, we only need to replace any instances of `useLayoutEffect` with `useIsomorphicEffect`.

**Comment by kenneth-duverge** [comment]
Fixed in this PR https://github.com/vimeo/iris/pull/222
