### ISSUE TITLE
[BUG]: TourPoint attach

### ISSUE THREAD

**Issue by siberry** [vimeo/iris#54]
### Description

Two issues:
~~1) It seems like top and bottom and right and left are switched around? Can be seen in [storybook](https://vimeo.github.io/iris/sb/main/?path=/story/components-info-tourpoint--controls&args=attach:right)~~
2) Attaching a tour point to the bottom of a component near the edge of the screen will go off the screen

### Steps to Reproduce

~~1) Check the attach options in Storybook. These seem inverted?~~
2) Add a tour point to an element near the edge of the screen. Ideally the tour point would be nudged to a few pixels in from the edge and the arrow would still point to the correct element.

### Storybook Demonstration

https://vimeo.github.io/iris/sb/main/?path=/story/components-info-tourpoint--controls&args=attach:right

### Version

0.109.0

**Comment by kenneth-duverge** [comment]
Take a quick look at those libraries and `react-tiny-popover` is the smallest in bundle size. The API looks pretty clean and intuitive.

| Package | Bundle size | Link |
|---------|-------------|------|
| `@floating-ui/react-dom`   | `20.7kb` |   https://bundlephobia.com/package/@floating-ui/react-dom@1.2.1   |
| `react-tiny-popover`   | `11.8kb` |   https://bundlephobia.com/package/react-tiny-popover@7.2.0  |
| `@popperjs/core`   | `20.9kb` |   https://bundlephobia.com/package/@popperjs/core@2.11.6  |

**Comment by Boughtmanatee5** [comment]
I like the `positions` priority prop. I was looking at fixing it and was thinking we'd have to check if there's more room on the left or right before moving it, but having the user set priorities means they can avoid covering important pieces of the page.

**Comment by Boughtmanatee5** [comment]
We can probably use `react-tiny-popover` and refactor TourPoint to use it. It might be a bigger change than fixing the bug though 🤔 .
