### ISSUE TITLE
[BUG]: TourPoint does not stay attached to anchor on screen resize

### ISSUE THREAD

**Issue by siberry** [vimeo/iris#67]
### Description

The TourPoint component does not stay attached to anchor on screen resize.

### Steps to Reproduce

Resize the canvas in Storybook

### Storybook Demonstration

https://vimeo.github.io/iris/sb/main/?path=/story/components-tourpoint--controls

### Version

0.114.0

**Comment by seanmcintyre** [comment]
resolved in `0.117.0`
