### ISSUE TITLE
[BUG]: Input type="number" is rendering <Mark />

### ISSUE THREAD

**Issue by Jwrighty** [vimeo/iris#85]
### Description

Input does not rendering correctly when passing type number. Looks like it's missing from the type switch statement and defaulting to the Mark component

### Steps to Reproduce

Render `<Input type="number" />` and you will get a Mark component return instead of an input element with type number

### Storybook Demonstration

https://vimeo.github.io/iris/sb/main/?path=/story/components-input--controls&args=type:number

### Version

0.117

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by seanmcintyre** [comment]
Out of curiosity, what are you using a number input for? It's possible our original intent was to dissuade its use or forbid it entirely via types. I recommend reading: https://bradfrost.com/blog/post/you-probably-dont-need-input-typenumber/.

**Comment by Jwrighty** [comment]
A couple of examples would be inputs to control x and y co-ordinates and height & width (pixel) values in the interactive overlay editor. And more recently an input to assign a score value to a question

**Comment by radderswwx** [comment]
Hi @seanmcintyre, this is something we've had another request for (adding arrow keys support for input boxes). I wanted to raise here to see if this bug is something that is going to be addressed or if we should look into a different solve. Thanks in advance!
